//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7MessageServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient_tbl()
        {
            this.Admissions = new HashSet<Admission_tbl>();
            this.RfidDetections = new HashSet<RfidDetection>();
        }
    
        public int patientId { get; set; }
        public int externalSourceId { get; set; }
        public string externalId { get; set; }
        public string givenName { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string sex { get; set; }
        public bool isMrsaPositive { get; set; }
        public bool isFallRisk { get; set; }
        public bool isAssistanceRequired { get; set; }
        public string assistanceDescription { get; set; }
        public bool hasLatexAllergy { get; set; }
        public string PID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission_tbl> Admissions { get; set; }
        public virtual ExternalSource ExternalSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RfidDetection> RfidDetections { get; set; }
    }
}
