//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7MessageServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staging_Admission
    {
        public string admissionExternalSource { get; set; }
        public string admissionExternalId { get; set; }
        public string admissionType { get; set; }
        public string admissionStatus { get; set; }
        public Nullable<System.DateTime> admitDateTime { get; set; }
        public Nullable<System.DateTime> dischargeDateTime { get; set; }
        public string patientExternalId { get; set; }
        public string patientGivenName { get; set; }
        public string patientSurname { get; set; }
        public string patientSex { get; set; }
        public Nullable<System.DateTime> patientDOB { get; set; }
        public bool isMrsaPositive { get; set; }
        public bool isFallRisk { get; set; }
        public bool isAssistanceRequired { get; set; }
        public string assistanceDescription { get; set; }
        public bool hasLatexAllergy { get; set; }
        public string location { get; set; }
        public string room { get; set; }
        public string bed { get; set; }
        public string doctorExternalSource { get; set; }
        public string attendingDoctorExternalId { get; set; }
        public string attendingDoctorName { get; set; }
        public string admittingDoctorExternalId { get; set; }
        public string admittingDoctorName { get; set; }
        public string primaryCareDoctorExternalId { get; set; }
        public string primaryCareDoctorName { get; set; }
    }
}
