

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Configuration : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Configuration entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Configuration()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Configuration(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Configuration.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int configurationId
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.configurationId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void configurationId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void configurationId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void configurationId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string name
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.name);
            }
            set
            {
                global::LightSwitchApplication.Configuration.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocations
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationLocations);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocationsQuery
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetQuery(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationLocations);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ConfigurationType ConfigurationType
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType);
            }
            set
            {
                global::LightSwitchApplication.Configuration.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConfigurationType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConfigurationType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ConfigurationType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Device> Devices
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.Devices);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Device> DevicesQuery
        {
            get
            {
                return global::LightSwitchApplication.Configuration.DetailsClass.GetQuery(this, global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.Devices);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Configuration,
                global::LightSwitchApplication.Configuration.DetailsClass,
                global::LightSwitchApplication.Configuration.DetailsClass.IImplementation,
                global::LightSwitchApplication.Configuration.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.configurationId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>.Entry
                __ConfigurationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>.Entry(
                    global::LightSwitchApplication.Configuration.DetailsClass.__Configuration_CreateNew,
                    global::LightSwitchApplication.Configuration.DetailsClass.__Configuration_Created,
                    global::LightSwitchApplication.Configuration.DetailsClass.__Configuration_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Configuration __Configuration_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration> es)
            {
                return new global::LightSwitchApplication.Configuration(es);
            }
            private static void __Configuration_Created(global::LightSwitchApplication.Configuration e)
            {
                e.Configuration_Created();
            }
            private static bool __Configuration_AllowSaveWithErrors(global::LightSwitchApplication.Configuration e)
            {
                bool result = false;
                e.Configuration_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Configuration.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int> configurationId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.configurationId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string> name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocations
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationLocations) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType> ConfigurationType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device> Devices
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.Devices) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int configurationId { get; }
                new string name { get; set; }
                new global::System.Collections.IEnumerable ConfigurationLocations { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ConfigurationType { get; set; }
                new global::System.Collections.IEnumerable Devices { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int>.Entry
                    configurationId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int>.Entry(
                        "configurationId",
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._configurationId_Stub,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._configurationId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._configurationId_Validate,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._configurationId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._configurationId_OnValueChanged);
                private static void _configurationId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int>.Data> c, global::LightSwitchApplication.Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._configurationId, sf);
                }
                private static bool _configurationId_ComputeIsReadOnly(global::LightSwitchApplication.Configuration e)
                {
                    bool result = false;
                    e.configurationId_IsReadOnly(ref result);
                    return result;
                }
                private static void _configurationId_Validate(global::LightSwitchApplication.Configuration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.configurationId_Validate(r);
                }
                private static int _configurationId_GetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.ImplementationEntity.configurationId;
                }
                private static void _configurationId_OnValueChanged(global::LightSwitchApplication.Configuration e)
                {
                    e.configurationId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string>.Entry
                    name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string>.Entry(
                        "name",
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_Stub,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_Validate,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_GetImplementationValue,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_SetImplementationValue,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._name_OnValueChanged);
                private static void _name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string>.Data> c, global::LightSwitchApplication.Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._name, sf);
                }
                private static bool _name_ComputeIsReadOnly(global::LightSwitchApplication.Configuration e)
                {
                    bool result = false;
                    e.name_IsReadOnly(ref result);
                    return result;
                }
                private static void _name_Validate(global::LightSwitchApplication.Configuration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.name_Validate(r);
                }
                private static string _name_GetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.ImplementationEntity.name;
                }
                private static void _name_SetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d, string v)
                {
                    d.ImplementationEntity.name = v;
                }
                private static void _name_OnValueChanged(global::LightSwitchApplication.Configuration e)
                {
                    e.name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Entry
                    ConfigurationLocations = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Entry(
                        "ConfigurationLocations",
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationLocations_Stub,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationLocations_GetReferencedEntities,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationLocations_GetEntityCollection);
                private static void _ConfigurationLocations_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Data> c, global::LightSwitchApplication.Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._ConfigurationLocations, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ConfigurationLocation> _ConfigurationLocations_GetReferencedEntities(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ConfigurationLocation, global::LightSwitchApplication.ConfigurationLocation.DetailsClass>(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationLocations, ref d._ConfigurationLocations);
                }
                private static global::System.Collections.IEnumerable _ConfigurationLocations_GetEntityCollection(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.ImplementationEntity.ConfigurationLocations;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType>.Entry
                    ConfigurationType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType>.Entry(
                        "ConfigurationType",
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_Stub,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_Validate,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_GetCoreImplementationValue,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_GetImplementationValue,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_SetImplementationValue,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_Refresh,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._ConfigurationType_OnValueChanged);
                private static void _ConfigurationType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType>.Data> c, global::LightSwitchApplication.Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._ConfigurationType, sf);
                }
                private static bool _ConfigurationType_ComputeIsReadOnly(global::LightSwitchApplication.Configuration e)
                {
                    bool result = false;
                    e.ConfigurationType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ConfigurationType_Validate(global::LightSwitchApplication.Configuration e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ConfigurationType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ConfigurationType_GetCoreImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.ImplementationEntity.ConfigurationType;
                }
                private static global::LightSwitchApplication.ConfigurationType _ConfigurationType_GetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ConfigurationType, global::LightSwitchApplication.ConfigurationType.DetailsClass>(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType, ref d._ConfigurationType);
                }
                private static void _ConfigurationType_SetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass d, global::LightSwitchApplication.ConfigurationType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType, ref d._ConfigurationType, (i, ev) => i.ConfigurationType = ev, v);
                }
                private static void _ConfigurationType_Refresh(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.ConfigurationType, ref d._ConfigurationType);
                }
                private static void _ConfigurationType_OnValueChanged(global::LightSwitchApplication.Configuration e)
                {
                    e.ConfigurationType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device>.Entry
                    Devices = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device>.Entry(
                        "Devices",
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._Devices_Stub,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._Devices_GetReferencedEntities,
                        global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties._Devices_GetEntityCollection);
                private static void _Devices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device>.Data> c, global::LightSwitchApplication.Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Devices, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Device> _Devices_GetReferencedEntities(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Device, global::LightSwitchApplication.Device.DetailsClass>(global::LightSwitchApplication.Configuration.DetailsClass.PropertySetProperties.Devices, ref d._Devices);
                }
                private static global::System.Collections.IEnumerable _Devices_GetEntityCollection(global::LightSwitchApplication.Configuration.DetailsClass d)
                {
                    return d.ImplementationEntity.Devices;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, int>.Data _configurationId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, string>.Data _name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Data _ConfigurationLocations;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.ConfigurationType>.Data _ConfigurationType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Configuration, global::LightSwitchApplication.Configuration.DetailsClass, global::LightSwitchApplication.Device>.Data _Devices;
            
        }
    
        #endregion
    }
    
    #endregion
}
