

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class ExternalSource : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ExternalSource entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExternalSource()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExternalSource(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExternalSource> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ExternalSource.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExternalSource_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ExternalSource_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int externalSourceId
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetValue(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.externalSourceId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void externalSourceId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void externalSourceId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void externalSourceId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string source
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetValue(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.source);
            }
            set
            {
                global::LightSwitchApplication.ExternalSource.DetailsClass.SetValue(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.source, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void source_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void source_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void source_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Procedure> Procedures
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetValue(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.Procedures);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Procedure> ProceduresQuery
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetQuery(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.Procedures);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProcedureCategory> ProcedureCategories
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetValue(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.ProcedureCategories);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProcedureCategory> ProcedureCategoriesQuery
        {
            get
            {
                return global::LightSwitchApplication.ExternalSource.DetailsClass.GetQuery(this, global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.ProcedureCategories);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ExternalSource,
                global::LightSwitchApplication.ExternalSource.DetailsClass,
                global::LightSwitchApplication.ExternalSource.DetailsClass.IImplementation,
                global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.externalSourceId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>.Entry
                __ExternalSourceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>.Entry(
                    global::LightSwitchApplication.ExternalSource.DetailsClass.__ExternalSource_CreateNew,
                    global::LightSwitchApplication.ExternalSource.DetailsClass.__ExternalSource_Created,
                    global::LightSwitchApplication.ExternalSource.DetailsClass.__ExternalSource_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ExternalSource __ExternalSource_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ExternalSource> es)
            {
                return new global::LightSwitchApplication.ExternalSource(es);
            }
            private static void __ExternalSource_Created(global::LightSwitchApplication.ExternalSource e)
            {
                e.ExternalSource_Created();
            }
            private static bool __ExternalSource_AllowSaveWithErrors(global::LightSwitchApplication.ExternalSource e)
            {
                bool result = false;
                e.ExternalSource_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int> externalSourceId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.externalSourceId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string> source
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.source) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure> Procedures
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.Procedures) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory> ProcedureCategories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.ProcedureCategories) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int externalSourceId { get; }
                new string source { get; set; }
                new global::System.Collections.IEnumerable Procedures { get; }
                new global::System.Collections.IEnumerable ProcedureCategories { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int>.Entry
                    externalSourceId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int>.Entry(
                        "externalSourceId",
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._externalSourceId_Stub,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._externalSourceId_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._externalSourceId_Validate,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._externalSourceId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._externalSourceId_OnValueChanged);
                private static void _externalSourceId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExternalSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int>.Data> c, global::LightSwitchApplication.ExternalSource.DetailsClass d, object sf)
                {
                    c(d, ref d._externalSourceId, sf);
                }
                private static bool _externalSourceId_ComputeIsReadOnly(global::LightSwitchApplication.ExternalSource e)
                {
                    bool result = false;
                    e.externalSourceId_IsReadOnly(ref result);
                    return result;
                }
                private static void _externalSourceId_Validate(global::LightSwitchApplication.ExternalSource e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.externalSourceId_Validate(r);
                }
                private static int _externalSourceId_GetImplementationValue(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.ImplementationEntity.externalSourceId;
                }
                private static void _externalSourceId_OnValueChanged(global::LightSwitchApplication.ExternalSource e)
                {
                    e.externalSourceId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string>.Entry
                    source = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string>.Entry(
                        "source",
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_Stub,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_ComputeIsReadOnly,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_Validate,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_GetImplementationValue,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_SetImplementationValue,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._source_OnValueChanged);
                private static void _source_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExternalSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string>.Data> c, global::LightSwitchApplication.ExternalSource.DetailsClass d, object sf)
                {
                    c(d, ref d._source, sf);
                }
                private static bool _source_ComputeIsReadOnly(global::LightSwitchApplication.ExternalSource e)
                {
                    bool result = false;
                    e.source_IsReadOnly(ref result);
                    return result;
                }
                private static void _source_Validate(global::LightSwitchApplication.ExternalSource e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.source_Validate(r);
                }
                private static string _source_GetImplementationValue(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.ImplementationEntity.source;
                }
                private static void _source_SetImplementationValue(global::LightSwitchApplication.ExternalSource.DetailsClass d, string v)
                {
                    d.ImplementationEntity.source = v;
                }
                private static void _source_OnValueChanged(global::LightSwitchApplication.ExternalSource e)
                {
                    e.source_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure>.Entry
                    Procedures = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure>.Entry(
                        "Procedures",
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._Procedures_Stub,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._Procedures_GetReferencedEntities,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._Procedures_GetEntityCollection);
                private static void _Procedures_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExternalSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure>.Data> c, global::LightSwitchApplication.ExternalSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Procedures, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Procedure> _Procedures_GetReferencedEntities(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Procedure, global::LightSwitchApplication.Procedure.DetailsClass>(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.Procedures, ref d._Procedures);
                }
                private static global::System.Collections.IEnumerable _Procedures_GetEntityCollection(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.ImplementationEntity.Procedures;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory>.Entry
                    ProcedureCategories = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory>.Entry(
                        "ProcedureCategories",
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._ProcedureCategories_Stub,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._ProcedureCategories_GetReferencedEntities,
                        global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties._ProcedureCategories_GetEntityCollection);
                private static void _ProcedureCategories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ExternalSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory>.Data> c, global::LightSwitchApplication.ExternalSource.DetailsClass d, object sf)
                {
                    c(d, ref d._ProcedureCategories, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProcedureCategory> _ProcedureCategories_GetReferencedEntities(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProcedureCategory, global::LightSwitchApplication.ProcedureCategory.DetailsClass>(global::LightSwitchApplication.ExternalSource.DetailsClass.PropertySetProperties.ProcedureCategories, ref d._ProcedureCategories);
                }
                private static global::System.Collections.IEnumerable _ProcedureCategories_GetEntityCollection(global::LightSwitchApplication.ExternalSource.DetailsClass d)
                {
                    return d.ImplementationEntity.ProcedureCategories;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, int>.Data _externalSourceId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, string>.Data _source;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.Procedure>.Data _Procedures;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ExternalSource, global::LightSwitchApplication.ExternalSource.DetailsClass, global::LightSwitchApplication.ProcedureCategory>.Data _ProcedureCategories;
            
        }
    
        #endregion
    }
    
    #endregion
}
