

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Location : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Location entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Location()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Location(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Location> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Location.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Location_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Location_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int locationId
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.locationId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void locationId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void locationId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void locationId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string code
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.code);
            }
            set
            {
                global::LightSwitchApplication.Location.DetailsClass.SetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.code, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void code_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void code_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void code_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string name
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.name);
            }
            set
            {
                global::LightSwitchApplication.Location.DetailsClass.SetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string patientType
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.patientType);
            }
            set
            {
                global::LightSwitchApplication.Location.DetailsClass.SetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.patientType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void patientType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void patientType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void patientType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string contactInfo
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.contactInfo);
            }
            set
            {
                global::LightSwitchApplication.Location.DetailsClass.SetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.contactInfo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void contactInfo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void contactInfo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void contactInfo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocations
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.ConfigurationLocations);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocationsQuery
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetQuery(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.ConfigurationLocations);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Device> Devices
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetValue(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.Devices);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Device> DevicesQuery
        {
            get
            {
                return global::LightSwitchApplication.Location.DetailsClass.GetQuery(this, global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.Devices);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Location,
                global::LightSwitchApplication.Location.DetailsClass,
                global::LightSwitchApplication.Location.DetailsClass.IImplementation,
                global::LightSwitchApplication.Location.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.locationId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>.Entry
                __LocationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>.Entry(
                    global::LightSwitchApplication.Location.DetailsClass.__Location_CreateNew,
                    global::LightSwitchApplication.Location.DetailsClass.__Location_Created,
                    global::LightSwitchApplication.Location.DetailsClass.__Location_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Location __Location_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Location> es)
            {
                return new global::LightSwitchApplication.Location(es);
            }
            private static void __Location_Created(global::LightSwitchApplication.Location e)
            {
                e.Location_Created();
            }
            private static bool __Location_AllowSaveWithErrors(global::LightSwitchApplication.Location e)
            {
                bool result = false;
                e.Location_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Location.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int> locationId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.locationId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string> code
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.code) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string> name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string> patientType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.patientType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string> contactInfo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.contactInfo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation> ConfigurationLocations
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.ConfigurationLocations) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device> Devices
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.Devices) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int locationId { get; }
                new string code { get; set; }
                new string name { get; set; }
                new string patientType { get; set; }
                new string contactInfo { get; set; }
                new global::System.Collections.IEnumerable ConfigurationLocations { get; }
                new global::System.Collections.IEnumerable Devices { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int>.Entry
                    locationId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int>.Entry(
                        "locationId",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._locationId_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._locationId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._locationId_Validate,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._locationId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._locationId_OnValueChanged);
                private static void _locationId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._locationId, sf);
                }
                private static bool _locationId_ComputeIsReadOnly(global::LightSwitchApplication.Location e)
                {
                    bool result = false;
                    e.locationId_IsReadOnly(ref result);
                    return result;
                }
                private static void _locationId_Validate(global::LightSwitchApplication.Location e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.locationId_Validate(r);
                }
                private static int _locationId_GetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.locationId;
                }
                private static void _locationId_OnValueChanged(global::LightSwitchApplication.Location e)
                {
                    e.locationId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry
                    code = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry(
                        "code",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_ComputeIsReadOnly,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_Validate,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_GetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_SetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._code_OnValueChanged);
                private static void _code_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._code, sf);
                }
                private static bool _code_ComputeIsReadOnly(global::LightSwitchApplication.Location e)
                {
                    bool result = false;
                    e.code_IsReadOnly(ref result);
                    return result;
                }
                private static void _code_Validate(global::LightSwitchApplication.Location e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.code_Validate(r);
                }
                private static string _code_GetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.code;
                }
                private static void _code_SetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d, string v)
                {
                    d.ImplementationEntity.code = v;
                }
                private static void _code_OnValueChanged(global::LightSwitchApplication.Location e)
                {
                    e.code_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry
                    name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry(
                        "name",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_Validate,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_GetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_SetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._name_OnValueChanged);
                private static void _name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._name, sf);
                }
                private static bool _name_ComputeIsReadOnly(global::LightSwitchApplication.Location e)
                {
                    bool result = false;
                    e.name_IsReadOnly(ref result);
                    return result;
                }
                private static void _name_Validate(global::LightSwitchApplication.Location e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.name_Validate(r);
                }
                private static string _name_GetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.name;
                }
                private static void _name_SetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d, string v)
                {
                    d.ImplementationEntity.name = v;
                }
                private static void _name_OnValueChanged(global::LightSwitchApplication.Location e)
                {
                    e.name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry
                    patientType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry(
                        "patientType",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_Validate,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_GetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_SetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._patientType_OnValueChanged);
                private static void _patientType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._patientType, sf);
                }
                private static bool _patientType_ComputeIsReadOnly(global::LightSwitchApplication.Location e)
                {
                    bool result = false;
                    e.patientType_IsReadOnly(ref result);
                    return result;
                }
                private static void _patientType_Validate(global::LightSwitchApplication.Location e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.patientType_Validate(r);
                }
                private static string _patientType_GetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.patientType;
                }
                private static void _patientType_SetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d, string v)
                {
                    d.ImplementationEntity.patientType = v;
                }
                private static void _patientType_OnValueChanged(global::LightSwitchApplication.Location e)
                {
                    e.patientType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry
                    contactInfo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Entry(
                        "contactInfo",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_Validate,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_GetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_SetImplementationValue,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._contactInfo_OnValueChanged);
                private static void _contactInfo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._contactInfo, sf);
                }
                private static bool _contactInfo_ComputeIsReadOnly(global::LightSwitchApplication.Location e)
                {
                    bool result = false;
                    e.contactInfo_IsReadOnly(ref result);
                    return result;
                }
                private static void _contactInfo_Validate(global::LightSwitchApplication.Location e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.contactInfo_Validate(r);
                }
                private static string _contactInfo_GetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.contactInfo;
                }
                private static void _contactInfo_SetImplementationValue(global::LightSwitchApplication.Location.DetailsClass d, string v)
                {
                    d.ImplementationEntity.contactInfo = v;
                }
                private static void _contactInfo_OnValueChanged(global::LightSwitchApplication.Location e)
                {
                    e.contactInfo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Entry
                    ConfigurationLocations = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Entry(
                        "ConfigurationLocations",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._ConfigurationLocations_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._ConfigurationLocations_GetReferencedEntities,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._ConfigurationLocations_GetEntityCollection);
                private static void _ConfigurationLocations_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._ConfigurationLocations, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ConfigurationLocation> _ConfigurationLocations_GetReferencedEntities(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ConfigurationLocation, global::LightSwitchApplication.ConfigurationLocation.DetailsClass>(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.ConfigurationLocations, ref d._ConfigurationLocations);
                }
                private static global::System.Collections.IEnumerable _ConfigurationLocations_GetEntityCollection(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.ConfigurationLocations;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device>.Entry
                    Devices = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device>.Entry(
                        "Devices",
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._Devices_Stub,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._Devices_GetReferencedEntities,
                        global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties._Devices_GetEntityCollection);
                private static void _Devices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Location.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device>.Data> c, global::LightSwitchApplication.Location.DetailsClass d, object sf)
                {
                    c(d, ref d._Devices, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Device> _Devices_GetReferencedEntities(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Device, global::LightSwitchApplication.Device.DetailsClass>(global::LightSwitchApplication.Location.DetailsClass.PropertySetProperties.Devices, ref d._Devices);
                }
                private static global::System.Collections.IEnumerable _Devices_GetEntityCollection(global::LightSwitchApplication.Location.DetailsClass d)
                {
                    return d.ImplementationEntity.Devices;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, int>.Data _locationId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data _code;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data _name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data _patientType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, string>.Data _contactInfo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.ConfigurationLocation>.Data _ConfigurationLocations;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Location, global::LightSwitchApplication.Location.DetailsClass, global::LightSwitchApplication.Device>.Data _Devices;
            
        }
    
        #endregion
    }
    
    #endregion
}
