//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 06/02/2012 17:34:22
namespace Cloudmaster.WCS.Iguana.Services
{
    
    /// <summary>
    /// There are no comments for IguanaDatabaseConnection in the schema.
    /// </summary>
    public partial class IguanaDatabaseConnection : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new IguanaDatabaseConnection object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public IguanaDatabaseConnection(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("IguanaDatabaseModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Cloudmaster.WCS.Iguana.Services", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Cloudmaster.WCS.Iguana.Services", global::System.StringComparison.Ordinal))
            {
                return string.Concat("IguanaDatabaseModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for OrderMessages in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrderMessage> OrderMessages
        {
            get
            {
                if ((this._OrderMessages == null))
                {
                    this._OrderMessages = base.CreateQuery<OrderMessage>("OrderMessages");
                }
                return this._OrderMessages;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrderMessage> _OrderMessages;
        /// <summary>
        /// There are no comments for Admissions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Admission> Admissions
        {
            get
            {
                if ((this._Admissions == null))
                {
                    this._Admissions = base.CreateQuery<Admission>("Admissions");
                }
                return this._Admissions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Admission> _Admissions;
        /// <summary>
        /// There are no comments for OrderMetadatas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OrderMetadata> OrderMetadatas
        {
            get
            {
                if ((this._OrderMetadatas == null))
                {
                    this._OrderMetadatas = base.CreateQuery<OrderMetadata>("OrderMetadatas");
                }
                return this._OrderMetadatas;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OrderMetadata> _OrderMetadatas;
        /// <summary>
        /// There are no comments for OrderMessages in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrderMessages(OrderMessage orderMessage)
        {
            base.AddObject("OrderMessages", orderMessage);
        }
        /// <summary>
        /// There are no comments for Admissions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAdmissions(Admission admission)
        {
            base.AddObject("Admissions", admission);
        }
        /// <summary>
        /// There are no comments for OrderMetadatas in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrderMetadatas(OrderMetadata orderMetadata)
        {
            base.AddObject("OrderMetadatas", orderMetadata);
        }
    }
    /// <summary>
    /// There are no comments for IguanaDatabaseModel.OrderMessage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OrderMessages")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class OrderMessage : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrderMessage object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrderMessage CreateOrderMessage(global::System.Guid ID)
        {
            OrderMessage orderMessage = new OrderMessage();
            orderMessage.id = ID;
            return orderMessage;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property orderControl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string orderControl
        {
            get
            {
                return this._orderControl;
            }
            set
            {
                this.OnorderControlChanging(value);
                this._orderControl = value;
                this.OnorderControlChanged();
                this.OnPropertyChanged("orderControl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _orderControl;
        partial void OnorderControlChanging(string value);
        partial void OnorderControlChanged();
        /// <summary>
        /// There are no comments for Property orderStatus in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string orderStatus
        {
            get
            {
                return this._orderStatus;
            }
            set
            {
                this.OnorderStatusChanging(value);
                this._orderStatus = value;
                this.OnorderStatusChanged();
                this.OnPropertyChanged("orderStatus");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _orderStatus;
        partial void OnorderStatusChanging(string value);
        partial void OnorderStatusChanged();
        /// <summary>
        /// There are no comments for Property placerOrderNumberEI in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string placerOrderNumberEI
        {
            get
            {
                return this._placerOrderNumberEI;
            }
            set
            {
                this.OnplacerOrderNumberEIChanging(value);
                this._placerOrderNumberEI = value;
                this.OnplacerOrderNumberEIChanged();
                this.OnPropertyChanged("placerOrderNumberEI");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _placerOrderNumberEI;
        partial void OnplacerOrderNumberEIChanging(string value);
        partial void OnplacerOrderNumberEIChanged();
        /// <summary>
        /// There are no comments for Property placerOrderNumberNS in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string placerOrderNumberNS
        {
            get
            {
                return this._placerOrderNumberNS;
            }
            set
            {
                this.OnplacerOrderNumberNSChanging(value);
                this._placerOrderNumberNS = value;
                this.OnplacerOrderNumberNSChanged();
                this.OnPropertyChanged("placerOrderNumberNS");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _placerOrderNumberNS;
        partial void OnplacerOrderNumberNSChanging(string value);
        partial void OnplacerOrderNumberNSChanged();
        /// <summary>
        /// There are no comments for Property placerOrderNumberUID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string placerOrderNumberUID
        {
            get
            {
                return this._placerOrderNumberUID;
            }
            set
            {
                this.OnplacerOrderNumberUIDChanging(value);
                this._placerOrderNumberUID = value;
                this.OnplacerOrderNumberUIDChanged();
                this.OnPropertyChanged("placerOrderNumberUID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _placerOrderNumberUID;
        partial void OnplacerOrderNumberUIDChanging(string value);
        partial void OnplacerOrderNumberUIDChanged();
        /// <summary>
        /// There are no comments for Property patientId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string patientId
        {
            get
            {
                return this._patientId;
            }
            set
            {
                this.OnpatientIdChanging(value);
                this._patientId = value;
                this.OnpatientIdChanged();
                this.OnPropertyChanged("patientId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _patientId;
        partial void OnpatientIdChanging(string value);
        partial void OnpatientIdChanged();
        /// <summary>
        /// There are no comments for Property familyName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string familyName
        {
            get
            {
                return this._familyName;
            }
            set
            {
                this.OnfamilyNameChanging(value);
                this._familyName = value;
                this.OnfamilyNameChanged();
                this.OnPropertyChanged("familyName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _familyName;
        partial void OnfamilyNameChanging(string value);
        partial void OnfamilyNameChanged();
        /// <summary>
        /// There are no comments for Property givenName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string givenName
        {
            get
            {
                return this._givenName;
            }
            set
            {
                this.OngivenNameChanging(value);
                this._givenName = value;
                this.OngivenNameChanged();
                this.OnPropertyChanged("givenName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _givenName;
        partial void OngivenNameChanging(string value);
        partial void OngivenNameChanged();
        /// <summary>
        /// There are no comments for Property secondAndFurtherGivenNames in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string secondAndFurtherGivenNames
        {
            get
            {
                return this._secondAndFurtherGivenNames;
            }
            set
            {
                this.OnsecondAndFurtherGivenNamesChanging(value);
                this._secondAndFurtherGivenNames = value;
                this.OnsecondAndFurtherGivenNamesChanged();
                this.OnPropertyChanged("secondAndFurtherGivenNames");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _secondAndFurtherGivenNames;
        partial void OnsecondAndFurtherGivenNamesChanging(string value);
        partial void OnsecondAndFurtherGivenNamesChanged();
        /// <summary>
        /// There are no comments for Property location in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this.OnlocationChanging(value);
                this._location = value;
                this.OnlocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _location;
        partial void OnlocationChanging(string value);
        partial void OnlocationChanged();
        /// <summary>
        /// There are no comments for Property room in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string room
        {
            get
            {
                return this._room;
            }
            set
            {
                this.OnroomChanging(value);
                this._room = value;
                this.OnroomChanged();
                this.OnPropertyChanged("room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _room;
        partial void OnroomChanging(string value);
        partial void OnroomChanged();
        /// <summary>
        /// There are no comments for Property bed in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string bed
        {
            get
            {
                return this._bed;
            }
            set
            {
                this.OnbedChanging(value);
                this._bed = value;
                this.OnbedChanged();
                this.OnPropertyChanged("bed");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _bed;
        partial void OnbedChanging(string value);
        partial void OnbedChanged();
        /// <summary>
        /// There are no comments for Property building in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string building
        {
            get
            {
                return this._building;
            }
            set
            {
                this.OnbuildingChanging(value);
                this._building = value;
                this.OnbuildingChanged();
                this.OnPropertyChanged("building");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _building;
        partial void OnbuildingChanging(string value);
        partial void OnbuildingChanged();
        /// <summary>
        /// There are no comments for Property floor in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string floor
        {
            get
            {
                return this._floor;
            }
            set
            {
                this.OnfloorChanging(value);
                this._floor = value;
                this.OnfloorChanged();
                this.OnPropertyChanged("floor");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _floor;
        partial void OnfloorChanging(string value);
        partial void OnfloorChanged();
        /// <summary>
        /// There are no comments for Property serviceId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string serviceId
        {
            get
            {
                return this._serviceId;
            }
            set
            {
                this.OnserviceIdChanging(value);
                this._serviceId = value;
                this.OnserviceIdChanged();
                this.OnPropertyChanged("serviceId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _serviceId;
        partial void OnserviceIdChanging(string value);
        partial void OnserviceIdChanged();
        /// <summary>
        /// There are no comments for Property serviceText in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string serviceText
        {
            get
            {
                return this._serviceText;
            }
            set
            {
                this.OnserviceTextChanging(value);
                this._serviceText = value;
                this.OnserviceTextChanged();
                this.OnPropertyChanged("serviceText");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _serviceText;
        partial void OnserviceTextChanging(string value);
        partial void OnserviceTextChanged();
        /// <summary>
        /// There are no comments for Property priority in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string priority
        {
            get
            {
                return this._priority;
            }
            set
            {
                this.OnpriorityChanging(value);
                this._priority = value;
                this.OnpriorityChanged();
                this.OnPropertyChanged("priority");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _priority;
        partial void OnpriorityChanging(string value);
        partial void OnpriorityChanged();
        /// <summary>
        /// There are no comments for Property requestedDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> requestedDateTime
        {
            get
            {
                return this._requestedDateTime;
            }
            set
            {
                this.OnrequestedDateTimeChanging(value);
                this._requestedDateTime = value;
                this.OnrequestedDateTimeChanged();
                this.OnPropertyChanged("requestedDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _requestedDateTime;
        partial void OnrequestedDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnrequestedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property observationDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> observationDateTime
        {
            get
            {
                return this._observationDateTime;
            }
            set
            {
                this.OnobservationDateTimeChanging(value);
                this._observationDateTime = value;
                this.OnobservationDateTimeChanged();
                this.OnPropertyChanged("observationDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _observationDateTime;
        partial void OnobservationDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnobservationDateTimeChanged();
        /// <summary>
        /// There are no comments for Property observationEndDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> observationEndDateTime
        {
            get
            {
                return this._observationEndDateTime;
            }
            set
            {
                this.OnobservationEndDateTimeChanging(value);
                this._observationEndDateTime = value;
                this.OnobservationEndDateTimeChanged();
                this.OnPropertyChanged("observationEndDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _observationEndDateTime;
        partial void OnobservationEndDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnobservationEndDateTimeChanged();
        /// <summary>
        /// There are no comments for Property dateCreated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateCreated
        {
            get
            {
                return this._dateCreated;
            }
            set
            {
                this.OndateCreatedChanging(value);
                this._dateCreated = value;
                this.OndateCreatedChanged();
                this.OnPropertyChanged("dateCreated");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateCreated;
        partial void OndateCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateCreatedChanged();
        /// <summary>
        /// There are no comments for Property dateOfBirth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateOfBirth
        {
            get
            {
                return this._dateOfBirth;
            }
            set
            {
                this.OndateOfBirthChanging(value);
                this._dateOfBirth = value;
                this.OndateOfBirthChanged();
                this.OnPropertyChanged("dateOfBirth");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateOfBirth;
        partial void OndateOfBirthChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateOfBirthChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IguanaDatabaseModel.Admission in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Admissions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Admission : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Admission object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Admission CreateAdmission(global::System.Guid ID)
        {
            Admission admission = new Admission();
            admission.id = ID;
            return admission;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property patientId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string patientId
        {
            get
            {
                return this._patientId;
            }
            set
            {
                this.OnpatientIdChanging(value);
                this._patientId = value;
                this.OnpatientIdChanged();
                this.OnPropertyChanged("patientId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _patientId;
        partial void OnpatientIdChanging(string value);
        partial void OnpatientIdChanged();
        /// <summary>
        /// There are no comments for Property dateOfBirth in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateOfBirth
        {
            get
            {
                return this._dateOfBirth;
            }
            set
            {
                this.OndateOfBirthChanging(value);
                this._dateOfBirth = value;
                this.OndateOfBirthChanged();
                this.OnPropertyChanged("dateOfBirth");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateOfBirth;
        partial void OndateOfBirthChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property visitId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string visitId
        {
            get
            {
                return this._visitId;
            }
            set
            {
                this.OnvisitIdChanging(value);
                this._visitId = value;
                this.OnvisitIdChanged();
                this.OnPropertyChanged("visitId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _visitId;
        partial void OnvisitIdChanging(string value);
        partial void OnvisitIdChanged();
        /// <summary>
        /// There are no comments for Property givenName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string givenName
        {
            get
            {
                return this._givenName;
            }
            set
            {
                this.OngivenNameChanging(value);
                this._givenName = value;
                this.OngivenNameChanged();
                this.OnPropertyChanged("givenName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _givenName;
        partial void OngivenNameChanging(string value);
        partial void OngivenNameChanged();
        /// <summary>
        /// There are no comments for Property familyName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string familyName
        {
            get
            {
                return this._familyName;
            }
            set
            {
                this.OnfamilyNameChanging(value);
                this._familyName = value;
                this.OnfamilyNameChanged();
                this.OnPropertyChanged("familyName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _familyName;
        partial void OnfamilyNameChanging(string value);
        partial void OnfamilyNameChanged();
        /// <summary>
        /// There are no comments for Property location in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string location
        {
            get
            {
                return this._location;
            }
            set
            {
                this.OnlocationChanging(value);
                this._location = value;
                this.OnlocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _location;
        partial void OnlocationChanging(string value);
        partial void OnlocationChanged();
        /// <summary>
        /// There are no comments for Property room in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string room
        {
            get
            {
                return this._room;
            }
            set
            {
                this.OnroomChanging(value);
                this._room = value;
                this.OnroomChanged();
                this.OnPropertyChanged("room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _room;
        partial void OnroomChanging(string value);
        partial void OnroomChanged();
        /// <summary>
        /// There are no comments for Property bed in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string bed
        {
            get
            {
                return this._bed;
            }
            set
            {
                this.OnbedChanging(value);
                this._bed = value;
                this.OnbedChanged();
                this.OnPropertyChanged("bed");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _bed;
        partial void OnbedChanging(string value);
        partial void OnbedChanged();
        /// <summary>
        /// There are no comments for Property admitDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> admitDateTime
        {
            get
            {
                return this._admitDateTime;
            }
            set
            {
                this.OnadmitDateTimeChanging(value);
                this._admitDateTime = value;
                this.OnadmitDateTimeChanged();
                this.OnPropertyChanged("admitDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _admitDateTime;
        partial void OnadmitDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnadmitDateTimeChanged();
        /// <summary>
        /// There are no comments for Property dischargeDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dischargeDateTime
        {
            get
            {
                return this._dischargeDateTime;
            }
            set
            {
                this.OndischargeDateTimeChanging(value);
                this._dischargeDateTime = value;
                this.OndischargeDateTimeChanged();
                this.OnPropertyChanged("dischargeDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dischargeDateTime;
        partial void OndischargeDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndischargeDateTimeChanged();
        /// <summary>
        /// There are no comments for Property dietType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string dietType
        {
            get
            {
                return this._dietType;
            }
            set
            {
                this.OndietTypeChanging(value);
                this._dietType = value;
                this.OndietTypeChanged();
                this.OnPropertyChanged("dietType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _dietType;
        partial void OndietTypeChanging(string value);
        partial void OndietTypeChanged();
        /// <summary>
        /// There are no comments for Property dateCreated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> dateCreated
        {
            get
            {
                return this._dateCreated;
            }
            set
            {
                this.OndateCreatedChanging(value);
                this._dateCreated = value;
                this.OndateCreatedChanged();
                this.OnPropertyChanged("dateCreated");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _dateCreated;
        partial void OndateCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OndateCreatedChanged();
        /// <summary>
        /// There are no comments for Property expectedLenghtOfStay in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> expectedLenghtOfStay
        {
            get
            {
                return this._expectedLenghtOfStay;
            }
            set
            {
                this.OnexpectedLenghtOfStayChanging(value);
                this._expectedLenghtOfStay = value;
                this.OnexpectedLenghtOfStayChanged();
                this.OnPropertyChanged("expectedLenghtOfStay");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _expectedLenghtOfStay;
        partial void OnexpectedLenghtOfStayChanging(global::System.Nullable<double> value);
        partial void OnexpectedLenghtOfStayChanged();
        /// <summary>
        /// There are no comments for Property acutalLenghtOfStay in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> acutalLenghtOfStay
        {
            get
            {
                return this._acutalLenghtOfStay;
            }
            set
            {
                this.OnacutalLenghtOfStayChanging(value);
                this._acutalLenghtOfStay = value;
                this.OnacutalLenghtOfStayChanged();
                this.OnPropertyChanged("acutalLenghtOfStay");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _acutalLenghtOfStay;
        partial void OnacutalLenghtOfStayChanging(global::System.Nullable<double> value);
        partial void OnacutalLenghtOfStayChanged();
        /// <summary>
        /// There are no comments for Property patientType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string patientType
        {
            get
            {
                return this._patientType;
            }
            set
            {
                this.OnpatientTypeChanging(value);
                this._patientType = value;
                this.OnpatientTypeChanged();
                this.OnPropertyChanged("patientType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _patientType;
        partial void OnpatientTypeChanging(string value);
        partial void OnpatientTypeChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for IguanaDatabaseModel.OrderMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OrderMetadatas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class OrderMetadata : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrderMetadata object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="isPrepWorkAcknowledged">Initial value of isPrepWorkAcknowledged.</param>
        /// <param name="isFastingAcknowledged">Initial value of isFastingAcknowledged.</param>
        /// <param name="isExamAcknowledged">Initial value of isExamAcknowledged.</param>
        /// <param name="isInjectionAcknowledged">Initial value of isInjectionAcknowledged.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OrderMetadata CreateOrderMetadata(global::System.Guid ID, bool isPrepWorkAcknowledged, bool isFastingAcknowledged, bool isExamAcknowledged, bool isInjectionAcknowledged)
        {
            OrderMetadata orderMetadata = new OrderMetadata();
            orderMetadata.id = ID;
            orderMetadata.isPrepWorkAcknowledged = isPrepWorkAcknowledged;
            orderMetadata.isFastingAcknowledged = isFastingAcknowledged;
            orderMetadata.isExamAcknowledged = isExamAcknowledged;
            orderMetadata.isInjectionAcknowledged = isInjectionAcknowledged;
            return orderMetadata;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property orderNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string orderNumber
        {
            get
            {
                return this._orderNumber;
            }
            set
            {
                this.OnorderNumberChanging(value);
                this._orderNumber = value;
                this.OnorderNumberChanged();
                this.OnPropertyChanged("orderNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _orderNumber;
        partial void OnorderNumberChanging(string value);
        partial void OnorderNumberChanged();
        /// <summary>
        /// There are no comments for Property isPrepWorkAcknowledged in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool isPrepWorkAcknowledged
        {
            get
            {
                return this._isPrepWorkAcknowledged;
            }
            set
            {
                this.OnisPrepWorkAcknowledgedChanging(value);
                this._isPrepWorkAcknowledged = value;
                this.OnisPrepWorkAcknowledgedChanged();
                this.OnPropertyChanged("isPrepWorkAcknowledged");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _isPrepWorkAcknowledged;
        partial void OnisPrepWorkAcknowledgedChanging(bool value);
        partial void OnisPrepWorkAcknowledgedChanged();
        /// <summary>
        /// There are no comments for Property isFastingAcknowledged in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool isFastingAcknowledged
        {
            get
            {
                return this._isFastingAcknowledged;
            }
            set
            {
                this.OnisFastingAcknowledgedChanging(value);
                this._isFastingAcknowledged = value;
                this.OnisFastingAcknowledgedChanged();
                this.OnPropertyChanged("isFastingAcknowledged");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _isFastingAcknowledged;
        partial void OnisFastingAcknowledgedChanging(bool value);
        partial void OnisFastingAcknowledgedChanged();
        /// <summary>
        /// There are no comments for Property isExamAcknowledged in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool isExamAcknowledged
        {
            get
            {
                return this._isExamAcknowledged;
            }
            set
            {
                this.OnisExamAcknowledgedChanging(value);
                this._isExamAcknowledged = value;
                this.OnisExamAcknowledgedChanged();
                this.OnPropertyChanged("isExamAcknowledged");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _isExamAcknowledged;
        partial void OnisExamAcknowledgedChanging(bool value);
        partial void OnisExamAcknowledgedChanged();
        /// <summary>
        /// There are no comments for Property requestedDateTimeOverride in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> requestedDateTimeOverride
        {
            get
            {
                return this._requestedDateTimeOverride;
            }
            set
            {
                this.OnrequestedDateTimeOverrideChanging(value);
                this._requestedDateTimeOverride = value;
                this.OnrequestedDateTimeOverrideChanged();
                this.OnPropertyChanged("requestedDateTimeOverride");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _requestedDateTimeOverride;
        partial void OnrequestedDateTimeOverrideChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnrequestedDateTimeOverrideChanged();
        /// <summary>
        /// There are no comments for Property notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string notes
        {
            get
            {
                return this._notes;
            }
            set
            {
                this.OnnotesChanging(value);
                this._notes = value;
                this.OnnotesChanged();
                this.OnPropertyChanged("notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _notes;
        partial void OnnotesChanging(string value);
        partial void OnnotesChanged();
        /// <summary>
        /// There are no comments for Property lastRequestedDateTimeOverrideModified in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> lastRequestedDateTimeOverrideModified
        {
            get
            {
                return this._lastRequestedDateTimeOverrideModified;
            }
            set
            {
                this.OnlastRequestedDateTimeOverrideModifiedChanging(value);
                this._lastRequestedDateTimeOverrideModified = value;
                this.OnlastRequestedDateTimeOverrideModifiedChanged();
                this.OnPropertyChanged("lastRequestedDateTimeOverrideModified");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _lastRequestedDateTimeOverrideModified;
        partial void OnlastRequestedDateTimeOverrideModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnlastRequestedDateTimeOverrideModifiedChanged();
        /// <summary>
        /// There are no comments for Property isInjectionAcknowledged in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool isInjectionAcknowledged
        {
            get
            {
                return this._isInjectionAcknowledged;
            }
            set
            {
                this.OnisInjectionAcknowledgedChanging(value);
                this._isInjectionAcknowledged = value;
                this.OnisInjectionAcknowledgedChanged();
                this.OnPropertyChanged("isInjectionAcknowledged");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _isInjectionAcknowledged;
        partial void OnisInjectionAcknowledgedChanging(bool value);
        partial void OnisInjectionAcknowledgedChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
