CREATE TABLE [dbo].[Staging_Order] (
    [orderExternalSource]  NVARCHAR (20)  NOT NULL,
    [orderExternalId]      NVARCHAR (20)  NOT NULL,
    [orderNumber]          NVARCHAR (50)  NULL,
    [department]           NVARCHAR (50)  NOT NULL,
    [procedureCategoryExternalId] NVARCHAR (20)  NULL,
    [procedureExternalId]  NVARCHAR (20)  NULL,
    [procedureCode]        NVARCHAR (20)  NULL,
    [procedureDescription] NVARCHAR (200) NULL,
    [procedureTime]        DATETIME       NULL,
    [status]               NVARCHAR (20)  NULL,
    [clinicalIndicators]   NVARCHAR (200) NULL,
	[completedDateTime]    DATETIME       NULL,
	[estimatedDuration]	   INT			  NULL,
    [admissionExternalSource] NVARCHAR (20)  NOT NULL,
    [admissionExternalId]  NVARCHAR (20)  NULL,
    [doctorExternalSource] NVARCHAR (20)  NOT NULL,
    [orderingDoctorExternalId] NVARCHAR (50)  NULL,
    [orderingDoctorName]   NVARCHAR (50)  NULL,
    [isHidden]             BIT            NOT NULL,
	[history]			   NVARCHAR(200)  NULL,
	[diagnosis]			   NVARCHAR(200)  NULL,
	[currentCardiologist]  NVARCHAR(200)  NULL,
	[requiresSupervision]  BIT NOT NULL DEFAULT(0),
	[requiresFootwear]  BIT NOT NULL DEFAULT(0),
	[requiresMedicalRecords]  BIT NOT NULL DEFAULT(0)
);