CREATE TABLE [dbo].[Staging_Admission] (
    [admissionExternalSource]    NVARCHAR (20) NOT NULL,
    [admissionExternalId]        NVARCHAR (20) NOT NULL,
    [admissionType]     NVARCHAR (20)  NULL,
    [admissionStatus]   NVARCHAR (20)  NULL,
    [admitDateTime]     DATETIME      NULL,
    [dischargeDateTime] DATETIME      NULL,
    [patientExternalId] NVARCHAR (20) NOT NULL,
    [patientGivenName]  NVARCHAR (50)  NULL,
    [patientSurname]    NVARCHAR (50)  NULL,
    [patientSex]        NVARCHAR (20) NULL,
	[patientDOB]        DATETIME      NULL,
    [isMrsaPositive]    BIT           NOT NULL,
    [isFallRisk]        BIT           NOT NULL,
    [isAssistanceRequired] BIT        NOT NULL,
    [assistanceDescription] NVARCHAR (50)  NULL,
    [hasLatexAllergy]   BIT           NOT NULL,
    [location]          NVARCHAR (20) NULL,
    [room]              NVARCHAR (50) NULL,
    [bed]               NVARCHAR (50) NULL,
    [doctorExternalSource]    NVARCHAR (20)  NOT NULL,
    [attendingDoctorExternalId] NVARCHAR (50) NULL,
    [attendingDoctorName] NVARCHAR (50) NULL,
    [admittingDoctorExternalId] NVARCHAR (50) NULL,
    [admittingDoctorName] NVARCHAR (50) NULL,
    [primaryCareDoctorExternalId] NVARCHAR (50) NULL,
    [primaryCareDoctorName] NVARCHAR (50) NULL
);

