ALTER TABLE [dbo].[AdmissionType]
    ADD CONSTRAINT [PK_AdmissionType] PRIMARY KEY CLUSTERED ([admissionTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

