ALTER TABLE [dbo].[Admission]
    ADD CONSTRAINT [PK_Admission] PRIMARY KEY CLUSTERED ([admissionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

