ALTER TABLE [dbo].[BedCleaningEventType]
    ADD CONSTRAINT [PK_BedCleaningEventType] PRIMARY KEY CLUSTERED ([bedCleaningEventTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

