ALTER TABLE [dbo].[DeviceConfiguration]
    ADD CONSTRAINT [PK_DeviceConfiguration] PRIMARY KEY CLUSTERED ([deviceId] ASC, [shortcutKeyNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

