ALTER TABLE [dbo].[Fake_Person]
    ADD CONSTRAINT [PK_Fake_Person] PRIMARY KEY CLUSTERED ([personId] ASC, [firstname] ASC, [surname] ASC, [dob] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

