ALTER TABLE [dbo].[NotificationType]
    ADD CONSTRAINT [PK_NotificationType] PRIMARY KEY CLUSTERED ([notificationTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
