ALTER TABLE [dbo].[Note]
    ADD CONSTRAINT [PK_Note] PRIMARY KEY CLUSTERED ([noteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

