ALTER TABLE [dbo].[Notification]
    ADD CONSTRAINT [PK_Notification] PRIMARY KEY CLUSTERED ([notificationId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

