ALTER TABLE [dbo].[Procedure]
    ADD CONSTRAINT [PK_Procedure] PRIMARY KEY CLUSTERED ([procedureId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

