ALTER TABLE [dbo].[Patient]
    ADD CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED ([patientId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

