ALTER TABLE [dbo].[Pin]
    ADD CONSTRAINT [PK_Pin] PRIMARY KEY CLUSTERED ([pinId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

