ALTER TABLE [dbo].[ProcedureCategory]
    ADD CONSTRAINT [PK_ProcedureCategory] PRIMARY KEY CLUSTERED ([procedureCategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

