ALTER TABLE [dbo].[RfidDetector]
    ADD CONSTRAINT [PK_RfidDetector] PRIMARY KEY CLUSTERED ([rfidDetectorId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
