ALTER TABLE [dbo].[RfidDirection]
    ADD CONSTRAINT [PK_RfidDirection] PRIMARY KEY CLUSTERED ([rfidDirectionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
