ALTER TABLE [dbo].[RfidDetection]
    ADD CONSTRAINT [PK_RfidDetection] PRIMARY KEY CLUSTERED ([rfidDetectionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

