ALTER TABLE [dbo].[Update]
    ADD CONSTRAINT [PK_Update] PRIMARY KEY CLUSTERED ([updateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

