//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H7Message
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int connectionId { get; set; }
        public System.DateTime connectionTime { get; set; }
        public int deviceId { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
