//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H7Message
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Connections = new HashSet<Connection>();
            this.DeviceConfigurations = new HashSet<DeviceConfiguration>();
            this.Pins = new HashSet<Pin>();
        }
    
        public int deviceId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string os { get; set; }
        public string clientVersion { get; set; }
        public string ipAddress { get; set; }
        public Nullable<System.DateTime> lastConnection { get; set; }
        public Nullable<int> locationId { get; set; }
        public int lockTimeout { get; set; }
        public int configurationTimeout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connection> Connections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceConfiguration> DeviceConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pin> Pins { get; set; }
        public virtual Location Location { get; set; }
    }
}
